name: social_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.6
  smooth_page_indicator: ^1.0.0+2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  like_button: ^2.0.4
  animated_bottom_navigation_bar: ^0.3.3
  google_fonts: ^2.3.3
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  readmore: ^2.1.0
  video_player:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/icons/
     - assets/images/

  fonts:
    - family: IconBroken
      fonts:
       - asset: assets/icons/icons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

